In [76]:
# Работа с текстом
# Векторизованные методы через str
# - lower, upper
# - strip, lstrip, rstrip
# - replace
# - contains
# - split
# - extract
# Данные с https://store.poidata.xyz/ru
# Задача:
# 0) Скачать датасет с store.poidata.xyz по России
# 1) Подсчитать кол-во адресов по регионам (столбец prov)
# - очиситить данные и привести к единообразию (нижний регистр и избаиться от типов региона)
# 2) Подсчитать домены верхнего уровня (ru, com, info ...) в столбце email
# 3) Из поля adr вытащить первое число

In [3]:
import pandas as pd
import numpy as np

In [4]:
df_raw = pd.read_csv('../data/raw/ru_sample.csv')

In [5]:
df_raw

,unique_id,poi_name,brand,poi_tel,super_category,main_category,location_id,area_id,small_area_id,latitude,...,postal,country,formatted_address,source_url,email,opening_hours,crawl_time,alternate_names,top_poi_score,top_source_urls
0,4314173,BIRACS Car Rental,NaN,+7 495 505 25 79,Motor Vehicle Manufacturing,Car rental,8510990020029,716330,851099002,55.71050,...,119334.0,RU,"Leninskiy Prospekt 30, Москва Moscow 119334 Ru...",https://rentmotors.ru/en,info@biracs.ru,"Mo,Tu,We,Th,Fr,Sa,Su 9 a.m.–6 p.m.",2025-09-05 09:28:00,Cheap Car Rentals;a car rental;is a car rental...,0.834822,https://rentmotors.ru/en | https://rentmotors....
1,4315598,Mebel' V Domodedovo,NaN,+7 930 830 27 68,Furniture and Home Furnishings Manufacturing,Furniture Store,8510785947306,716313,851078594,55.31200,...,142050.0,RU,"Kashirskoye Shosse 17а, Domodedovo Домодедово ...",https://mebel-domodedovo.ru/,zakaz@mebel-domodedovo.ru,"Mo,Tu,We,Th,Fr,Sa,Su 10 a.m.–8 p.m.",2025-09-06 23:59:39,Мебель в Домодедово;мебели в Домодедово;Makers...,0.786267,https://mebel-domodedovo.ru/ | http://www.mebe...
2,4317215,Magnat,NaN,+7 965 487 91 70,Food and Beverage Services,Grocery Store,8473892863554,713208,847389286,42.19980,...,368628.0,RU,"Строительная улица 15, Падар Весенняя 368628, RU",https://soleniyamagnat.ru/contacts,info@soleniyamagnat.ru,"Su Closed; Mo,Tu,We,Th,Fr,Sa 8 a.m.–6 p.m.",2025-09-14 18:52:52,МАГНАТ;Магнат';MAGNIT;Магнат-РБ;magnat.ru,0.789244,https://spark-interfax.ru/dagestan-respublika-...
3,4318042,Ooo 'Moskit-2',NaN,+7 861 231 65 94,Retail,Hardware Store,8466058002847,712548,846605800,45.02430,...,350018.0,RU,"ul. Sormovskaya 3/7, Краснодар Krasnodar 35001...",https://yandex.com/maps/org/moskit_2/103187707...,krasnodar@moskit.info,"Sa,Su Closed; Mo,Tu,We,Th,Fr 8 a.m.–5 p.m.",2025-09-18 21:43:53,of Moskit-2;MOSKIT-2;Москит-2,0.802397,https://yandex.com/maps/org/moskit_2/103187707...
4,4322091,Vostok-Servis,NaN,+7 423 242 96 00,Retail,Workwear Store,8039580463589,676653,803958046,43.12823,...,690106.0,RU,"Prospekt Krasnogo Znameni 34, Vladivostok Влад...",https://vladivostok.ruspravochnik.com/company/...,complect@vladivostok.ru,"Mo,Tu,We,Th,Fr 8:30 AM–6 PM; Sa,Su Closed",2025-09-16 03:19:26,VOSTOK-SERVIS;Восток-Сервис;Vostok-Service;PRI...,0.892040,https://vladivostok.ruspravochnik.com/company/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1365,1054188,Киви Дент,NaN,+7 499 288 76 65,Medical Equipment Manufacturing,Dental Clinic,8510991355299,716330,851099135,55.67870,...,115533.0,Russia,"Высокая улица 4, Москва 115533 moscow, Russia",https://yandex.ru/maps/org/kiwi_dent/137030015...,info@kiwident.ru,"ежедневно, 09:00–21:00",2025-10-01 09:31:22,Kiwi Dent;КИВИ-ДЕНТ,0.750309,https://prodoctorov.ru/moskva/lpu/59692-kivi-d...
1366,1739822,Rostovskiy Gosudarstvennyy Ekonomicheskiy Univ...,NaN,+7 878 226 11 51,Higher Education,University,8470734956345,712942,847073495,44.23180,...,369000.0,RU,"Krasnaya Ulitsa 3, Черкесск Cherkessk 369000, RU",https://yandex.com/maps/org/rostovsky_gosudars...,interoffice.rsue@gmail.com,"Mo,Tu,We,Th,Fr: 9a.m.-5p.m.",2025-09-05 05:06:44,Rostovsky gosudarstvenny ekonomichesky univers...,0.713371,https://yandex.com/maps/org/rostovsky_gosudars...
1367,1234649,Liquy Moly,NaN,+7 988 206 13 60,Motor Vehicle Manufacturing,Oil Change,8473050334029,713137,847305033,42.97700,...,367027.0,RU,"пос Семендер, Makhachkala 367027 Republic of D...",https://www.facebook.com/LIQUIMOLYTASHKENT/fol...,support.north-america@liqui-moly.com,"Mo,Tu,We,Th,Sa,Su 9–10a.m.; Fr 2p.m.–12a.m.",2025-09-17 20:18:04,LIQUI MOLY,0.725000,https://www.facebook.com/LIQUIMOLYTASHKENT/fol...
1368,1700314,Departament Fizicheskoy Kul'tury I Sporta,NaN,+7 495 624 99 13,Government Administration,Government office,8510992827917,716330,851099282,55.76140,...,125032.0,RU,"Tverskaya St 13, Москва Moscow 125032 Russia, RU",https://www.withcountry.com/rus/item-899331-up...,fizkult@teoriya.ru,"Sa,Su Closed; Mo,Tu,We,Th,Fr 8:43a.m.–5:...",2025-09-09 13:28:38,Universitet Fizičeskoj Kultury: Sporta;Upravle...,0.674750,https://www.withcountry.com/rus/item-899331-up...
1369,1236859,Grand Boutique,NaN,+7 473 255 44 92,Retail,Store,8463276215630,712314,846327621,51.66070,...,394036.0,RU,"Lenina Square 15, Voronezh 394036 Voronezh Obl...",https://grandeboutique.ru/,grand_boutique@mail.ru,"Su 11a.m.–6p.m.; Mo,Tu,We,Th,Fr,Sa 10a.m...",2025-09-20 05:47:25,Grand Butique;GRAND boutique;grand_boutique_vr...,0.750329,https://wanderlog.com/place/details/4081506/gr...

In [27]:
df_city = df_raw[['city', 'neighborhood']].copy()

In [28]:
df_city

             city neighborhood
0          Москва       Moscow
1      Domodedovo   Домодедово
2           Падар     Весенняя
3       Краснодар    Krasnodar
4     Vladivostok  Владивосток
...           ...          ...
1365       Москва          NaN
1366     Черкесск    Cherkessk
1367  Makhachkala          NaN
1368       Москва       Moscow
1369     Voronezh          NaN

[1370 rows x 2 columns]

In [29]:
df_city['city_clean'] = df_city['city'].str.lower()
df_city['neighborhood_clean'] = df_city['neighborhood'].str.lower()

In [30]:
df_city[df_city['city']=='г. Москва']

          city neighborhood city_clean neighborhood_clean
366  г. Москва       Moscow  г. москва             moscow

In [31]:
bad_words = [
    'г.',
    'с.',
    'сельское поселение',
    'городской округ',
    'город',
    'район',
    'поселок',
]

In [32]:
for word in bad_words:
    df_city['city_clean'] = df_city['city_clean'].str.replace(word, '')
    df_city['neighborhood_clean'] = df_city['neighborhood_clean'].str.replace(word, '')

In [33]:
df_city[df_city['city']=='г. Москва']

          city neighborhood city_clean neighborhood_clean
366  г. Москва       Moscow     москва             moscow

In [34]:
df_city['city_clean'] = df_city['city_clean'].str.strip()
df_city['neighborhood_clean'] = df_city['neighborhood_clean'].str.strip()

In [35]:
df_city[df_city['city']=='г. Москва']

          city neighborhood city_clean neighborhood_clean
366  г. Москва       Moscow     москва             moscow

In [38]:
df_city[df_city['city'].str.contains('Москва')]['city'].unique()

array(['Москва', 'г. Москва'], dtype=object)

In [42]:
pat_rus = '[а-я]'
df_city['city_is_rus'] = df_city['city_clean'].str.contains(pat_rus)
df_city['neighborhood_is_rus'] = df_city['neighborhood_clean'].str.contains(pat_rus)

In [43]:
df_city

,city,neighborhood,city_clean,neighborhood_clean,city_is_rus,neighborhood_is_rus
0,Москва,Moscow,москва,moscow,True,False
1,Domodedovo,Домодедово,domodedovo,домодедово,False,True
2,Падар,Весенняя,падар,весенняя,True,True
3,Краснодар,Krasnodar,краснодар,krasnodar,True,False
4,Vladivostok,Владивосток,vladivostok,владивосток,False,True
...,...,...,...,...,...,...
1365,Москва,NaN,москва,NaN,True,NaN
1366,Черкесск,Cherkessk,черкесск,cherkessk,True,False
1367,Makhachkala,NaN,makhachkala,NaN,False,NaN
1368,Москва,Moscow,москва,moscow,True,False
1369,Voronezh,NaN,voronezh,NaN,False,NaN

In [45]:
def select_city_rus(row):
    if row['city_is_rus']:
        return row['city_clean']
    elif row['neighborhood_is_rus']:
        return row['neighborhood_clean']
    else:
        return np.nan

In [47]:
df_city['city_rus'] = df_city.apply(select_city_rus, axis=1)

In [50]:
df_city[['city', 'neighborhood', 'city_rus']]

             city neighborhood     city_rus
0          Москва       Moscow       москва
1      Domodedovo   Домодедово   домодедово
2           Падар     Весенняя        падар
3       Краснодар    Krasnodar    краснодар
4     Vladivostok  Владивосток  владивосток
...           ...          ...          ...
1365       Москва          NaN       москва
1366     Черкесск    Cherkessk     черкесск
1367  Makhachkala          NaN          NaN
1368       Москва       Moscow       москва
1369     Voronezh          NaN          NaN

[1370 rows x 3 columns]

In [60]:
df_city['city_rus'].value_counts()

city_rus
москва             214
санкт-петербург    109
краснодар           33
новосибирск         31
ростов-на-дону      23
                  ...
лесозаводск          1
березовка            1
троицк               1
омутнинск            1
черкесск             1
Name: count, Length: 307, dtype: int64

In [61]:
df_2 = df_raw[['email']].copy()

In [62]:
df_2

                                     email
0                           info@biracs.ru
1                zakaz@mebel-domodedovo.ru
2                   info@soleniyamagnat.ru
3                    krasnodar@moskit.info
4                  complect@vladivostok.ru
...                                    ...
1365                      info@kiwident.ru
1366            interoffice.rsue@gmail.com
1367  support.north-america@liqui-moly.com
1368                    fizkult@teoriya.ru
1369                grand_boutique@mail.ru

[1370 rows x 1 columns]

In [64]:
df_2['email'].str.split('@', expand=True)

                          0                    1
0                      info            biracs.ru
1                     zakaz  mebel-domodedovo.ru
2                      info    soleniyamagnat.ru
3                 krasnodar          moskit.info
4                  complect       vladivostok.ru
...                     ...                  ...
1365                   info          kiwident.ru
1366       interoffice.rsue            gmail.com
1367  support.north-america       liqui-moly.com
1368                fizkult           teoriya.ru
1369         grand_boutique              mail.ru

[1370 rows x 2 columns]

In [65]:
df_2['email_name'] = df_2['email'].str.split('@', expand=True)[0]
df_2['email_domain'] = df_2['email'].str.split('@', expand=True)[1]

In [66]:
df_2

,email,email_name,email_domain
0,info@biracs.ru,info,biracs.ru
1,zakaz@mebel-domodedovo.ru,zakaz,mebel-domodedovo.ru
2,info@soleniyamagnat.ru,info,soleniyamagnat.ru
3,krasnodar@moskit.info,krasnodar,moskit.info
4,complect@vladivostok.ru,complect,vladivostok.ru
...,...,...,...
1365,info@kiwident.ru,info,kiwident.ru
1366,interoffice.rsue@gmail.com,interoffice.rsue,gmail.com
1367,support.north-america@liqui-moly.com,support.north-america,liqui-moly.com
1368,fizkult@teoriya.ru,fizkult,teoriya.ru
1369,grand_boutique@mail.ru,grand_boutique,mail.ru

In [67]:
df_3 = df_raw[['formatted_address']].copy()

In [72]:
pat_postal_code = r'(\d{6})'

In [74]:
df_3['postal_code'] = df_3['formatted_address'].str.extract(pat_postal_code)

In [75]:
df_3

                                      formatted_address postal_code
0     Leninskiy Prospekt 30, Москва Moscow 119334 Ru...      119334
1     Kashirskoye Shosse 17а, Domodedovo Домодедово ...      142050
2      Строительная улица 15, Падар Весенняя 368628, RU      368628
3     ul. Sormovskaya 3/7, Краснодар Krasnodar 35001...      350018
4     Prospekt Krasnogo Znameni 34, Vladivostok Влад...      690106
...                                                 ...         ...
1365      Высокая улица 4, Москва 115533 moscow, Russia      115533
1366   Krasnaya Ulitsa 3, Черкесск Cherkessk 369000, RU      369000
1367  пос Семендер, Makhachkala 367027 Republic of D...      367027
1368   Tverskaya St 13, Москва Moscow 125032 Russia, RU      125032
1369  Lenina Square 15, Voronezh 394036 Voronezh Obl...      394036

[1370 rows x 2 columns]