In [1]:
import pandas as pd

In [102]:
# 1) Разворачивание (заворачивание) данных
# - melt
# - pivot
# 2) Преобразование типов
# - pd.to_numeric
# - pd.to_datetime
# 3) Работа с Nan
# - fillna
# - dropna
# 4) Группировка
# - groupby

# Задание:
# 1) Скачать показатель с https://www.gapminder.org/data/
# 2) Преоброзовать в длинный формат
# 3) Удалить null, если есть
# 4) Сделать Группировка

In [4]:
df = pd.read_csv('../data/raw/aged_15plus_unemployment_rate_percent.csv')

In [5]:
df

,country,1947,1948,1949,1950,1951,1952,1953,1954,1955,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.69,NaN,7.91,NaN,NaN,11.2,NaN,NaN,11.7
2,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.36,NaN,NaN,9.58,NaN,NaN,NaN,NaN,NaN,NaN
3,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.50,13.40,15.9,18.10,17.2,15.4,13.6,12.3,11.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.68,8.75,NaN,8.72,NaN,NaN,14.5,NaN,NaN,NaN
218,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,13.50,NaN,NaN,NaN,NaN,NaN,NaN
219,South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.60,24.70,24.6,24.90,25.1,26.5,27.0,26.9,28.5,29.2
220,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.85,NaN,NaN,NaN,NaN,11.6,12.0,12.5,NaN
221,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.37,NaN,NaN,4.77,NaN,NaN,NaN,NaN,16.9,NaN

In [12]:
# pivot - длиннный -> широкий
# melt - широкий -> длиннный

In [22]:
df_melt = pd.melt(
        df, 
        id_vars='country', 
        var_name='year',
        value_name='unemployment_15plus'
)

In [23]:
df_melt

            country  year  unemployment_15plus
0             Aruba  1947                  NaN
1       Afghanistan  1947                  NaN
2            Angola  1947                  NaN
3          Anguilla  1947                  NaN
4           Albania  1947                  NaN
...             ...   ...                  ...
16423         Samoa  2020                  NaN
16424         Yemen  2020                  NaN
16425  South Africa  2020                 29.2
16426        Zambia  2020                  NaN
16427      Zimbabwe  2020                  NaN

[16428 rows x 3 columns]

In [27]:
df_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16428 entries, 0 to 16427
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              16428 non-null  object
 1   year                 16428 non-null  object
 2   unemployment_15plus  4698 non-null   float64
dtypes: float64(1), object(2)
memory usage: 385.2+ KB

In [28]:
df_melt['year'] = pd.to_numeric(df_melt['year'])

In [30]:
help(pd.to_numeric)

Help on function to_numeric in module pandas.core.tools.numeric:

to_numeric(arg, errors: 'DateTimeErrorChoices' = 'raise', downcast: "Literal['integer', 'signed', 'unsigned', 'float'] | None" = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>)
    Convert argument to a numeric type.

    The default return dtype is `float64` or `int64`
    depending on the data supplied. Use the `downcast` parameter
    to obtain other dtypes.

    Please note that precision loss may occur if really large numbers
    are passed in. Due to the internal limitations of `ndarray`, if
    numbers smaller than `-9223372036854775808` (np.iinfo(np.int64).min)
    or larger than `18446744073709551615` (np.iinfo(np.uint64).max) are
    passed in, it is very likely they will be converted to float so that
    they can be stored in an `ndarray`. These warnings apply similarly to
    `Series` since it internally leverages `ndarray`.

    Parameters
    ----------
    arg : scalar, list, tuple, 1-d array, or Series
        Argument to be converted.
    errors : {'ignore', 'raise', 'coerce'}, default 'raise'
        - If 'raise', then invalid parsing will raise an exception.
        - If 'coerce', then invalid parsing will be set as NaN.
        - If 'ignore', then invalid parsing will return the input.

        .. versionchanged:: 2.2

        "ignore" is deprecated. Catch exceptions explicitly instead.

    downcast : str, default None
        Can be 'integer', 'signed', 'unsigned', or 'float'.
        If not None, and if the data has been successfully cast to a
        numerical dtype (or if the data was numeric to begin with),
        downcast that resulting data to the smallest numerical dtype
        possible according to the following rules:

        - 'integer' or 'signed': smallest signed int dtype (min.: np.int8)
        - 'unsigned': smallest unsigned int dtype (min.: np.uint8)
        - 'float': smallest float dtype (min.: np.float32)

        As this behaviour is separate from the core conversion to
        numeric values, any errors raised during the downcasting
        will be surfaced regardless of the value of the 'errors' input.

        In addition, downcasting will only occur if the size
        of the resulting data's dtype is strictly larger than
        the dtype it is to be cast to, so if none of the dtypes
        checked satisfy that specification, no downcasting will be
        performed on the data.
    dtype_backend : {'numpy_nullable', 'pyarrow'}, default 'numpy_nullable'
        Back-end data type applied to the resultant :class:`DataFrame`
        (still experimental). Behaviour is as follows:

        * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
          (default).
        * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
          DataFrame.

        .. versionadded:: 2.0

    Returns
    -------
    ret
        Numeric if parsing succeeded.
        Return type depends on input.  Series if Series, otherwise ndarray.

    See Also
    --------
    DataFrame.astype : Cast argument to a specified dtype.
    to_datetime : Convert argument to datetime.
    to_timedelta : Convert argument to timedelta.
    numpy.ndarray.astype : Cast a numpy array to a specified type.
    DataFrame.convert_dtypes : Convert dtypes.

    Examples
    --------
    Take separate series and convert to numeric, coercing when told to

    >>> s = pd.Series(['1.0', '2', -3])
    >>> pd.to_numeric(s)
    0    1.0
    1    2.0
    2   -3.0
    dtype: float64
    >>> pd.to_numeric(s, downcast='float')
    0    1.0
    1    2.0
    2   -3.0
    dtype: float32
    >>> pd.to_numeric(s, downcast='signed')
    0    1
    1    2
    2   -3
    dtype: int8
    >>> s = pd.Series(['apple', '1.0', '2', -3])
    >>> pd.to_numeric(s, errors='coerce')
    0    NaN
    1    1.0
    2    2.0
    3   -3.0
    dtype: float64

    Downcasting of nullable integer and floating dtypes is supported:

    >>> s = pd.Series([1, 2, 3], dtype="Int64")
    >>> pd.to_numeric(s, downcast="integer")
    0    1
    1    2
    2    3
    dtype: Int8
    >>> s = pd.Series([1.0, 2.1, 3.0], dtype="Float64")
    >>> pd.to_numeric(s, downcast="float")
    0    1.0
    1    2.1
    2    3.0
    dtype: Float32

In [31]:
df_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16428 entries, 0 to 16427
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              16428 non-null  object
 1   year                 16428 non-null  int64
 2   unemployment_15plus  4698 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 385.2+ KB

In [ ]:
# 1) Удалить - dropna
# 2) Заполнить - fillna

In [35]:
mean_unemployment_15plus_world = df_melt['unemployment_15plus'].mean()

In [36]:
mean_unemployment_15plus_world

np.float64(8.439333759046402)

In [37]:
df_2 = df_melt.copy()

In [39]:
df_2['unemployment_15plus'] = df_2['unemployment_15plus'].fillna(mean_unemployment_15plus_world)

In [40]:
df_2

            country  year  unemployment_15plus
0             Aruba  1947             8.439334
1       Afghanistan  1947             8.439334
2            Angola  1947             8.439334
3          Anguilla  1947             8.439334
4           Albania  1947             8.439334
...             ...   ...                  ...
16423         Samoa  2020             8.439334
16424         Yemen  2020             8.439334
16425  South Africa  2020            29.200000
16426        Zambia  2020             8.439334
16427      Zimbabwe  2020             8.439334

[16428 rows x 3 columns]

In [41]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16428 entries, 0 to 16427
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              16428 non-null  object
 1   year                 16428 non-null  int64
 2   unemployment_15plus  16428 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 385.2+ KB

In [33]:
help(pd.DataFrame.fillna)

Help on function fillna in module pandas.core.generic:

fillna(self, value: 'Hashable | Mapping | Series | DataFrame | None' = None, *, method: 'FillnaOptions | None' = None, axis: 'Axis | None' = None, inplace: 'bool_t' = False, limit: 'int | None' = None, downcast: 'dict | None | lib.NoDefault' = <no_default>) -> 'Self | None'
    Fill NA/NaN values using the specified method.

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame).  Values not
        in the dict/Series/DataFrame will not be filled. This value cannot
        be a list.
    method : {'backfill', 'bfill', 'ffill', None}, default None
        Method to use for filling holes in reindexed Series:

        * ffill: propagate last valid observation forward to next valid.
        * backfill / bfill: use next valid observation to fill gap.

        .. deprecated:: 2.1.0
            Use ffill or bfill instead.

    axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
        Axis along which to fill missing values. For `Series`
        this parameter is unused and defaults to 0.
    inplace : bool, default False
        If True, fill in-place. Note: this will modify any
        other views on this object (e.g., a no-copy slice for a column in a
        DataFrame).
    limit : int, default None
        If method is specified, this is the maximum number of consecutive
        NaN values to forward/backward fill. In other words, if there is
        a gap with more than this number of consecutive NaNs, it will only
        be partially filled. If method is not specified, this is the
        maximum number of entries along the entire axis where NaNs will be
        filled. Must be greater than 0 if not None.
    downcast : dict, default is None
        A dict of item->dtype of what to downcast if possible,
        or the string 'infer' which will try to downcast to an appropriate
        equal type (e.g. float64 to int64 if possible).

        .. deprecated:: 2.2.0

    Returns
    -------
    Series/DataFrame or None
        Object with missing values filled or None if ``inplace=True``.

    See Also
    --------
    ffill : Fill values by propagating the last valid observation to next valid.
    bfill : Fill values by using the next valid observation to fill the gap.
    interpolate : Fill NaN values using interpolation.
    reindex : Conform object to new index.
    asfreq : Convert TimeSeries to specified frequency.

    Examples
    --------
    >>> df = pd.DataFrame([[np.nan, 2, np.nan, 0],
    ...                    [3, 4, np.nan, 1],
    ...                    [np.nan, np.nan, np.nan, np.nan],
    ...                    [np.nan, 3, np.nan, 4]],
    ...                   columns=list("ABCD"))
    >>> df
         A    B   C    D
    0  NaN  2.0 NaN  0.0
    1  3.0  4.0 NaN  1.0
    2  NaN  NaN NaN  NaN
    3  NaN  3.0 NaN  4.0

    Replace all NaN elements with 0s.

    >>> df.fillna(0)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  0.0
    3  0.0  3.0  0.0  4.0

    Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
    2, and 3 respectively.

    >>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
    >>> df.fillna(value=values)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  2.0  1.0
    2  0.0  1.0  2.0  3.0
    3  0.0  3.0  2.0  4.0

    Only replace the first NaN element.

    >>> df.fillna(value=values, limit=1)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  NaN  1.0
    2  NaN  1.0  NaN  3.0
    3  NaN  3.0  NaN  4.0

    When filling using a DataFrame, replacement happens along
    the same column names and same indices

    >>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
    >>> df.fillna(df2)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  NaN
    3  0.0  3.0  0.0  4.0

    Note that column D is not affected since it is not present in df2.

In [32]:
help(pd.DataFrame.dropna)

Help on function dropna in module pandas.core.frame:

dropna(self, *, axis: 'Axis' = 0, how: 'AnyAll | lib.NoDefault' = <no_default>, thresh: 'int | lib.NoDefault' = <no_default>, subset: 'IndexLabel | None' = None, inplace: 'bool' = False, ignore_index: 'bool' = False) -> 'DataFrame | None'
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or sequence of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
    ...                    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    ...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
    ...                             pd.NaT]})
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis='columns')
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how='all')
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=['name', 'toy'])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

In [43]:
df_3 = df_melt.copy()
df_4 = df_melt.copy()

In [45]:
df_3 = df_3.dropna()

In [47]:
df_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16428 entries, 0 to 16427
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              16428 non-null  object
 1   year                 16428 non-null  int64
 2   unemployment_15plus  4698 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 385.2+ KB

In [48]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4698 entries, 209 to 16425
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              4698 non-null   object
 1   year                 4698 non-null   int64
 2   unemployment_15plus  4698 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 146.8+ KB

In [49]:
df_4 = df_4.dropna(axis=1)

In [50]:
df_4

            country  year
0             Aruba  1947
1       Afghanistan  1947
2            Angola  1947
3          Anguilla  1947
4           Albania  1947
...             ...   ...
16423         Samoa  2020
16424         Yemen  2020
16425  South Africa  2020
16426        Zambia  2020
16427      Zimbabwe  2020

[16428 rows x 2 columns]

In [51]:
df_3

            country  year  unemployment_15plus
209             USA  1947                 3.90
431             USA  1948                 3.80
653             USA  1949                 5.90
875             USA  1950                 5.30
1097            USA  1951                 3.30
...             ...   ...                  ...
16413       Ukraine  2020                 9.48
16414       Uruguay  2020                10.50
16415           USA  2020                 8.05
16420       Vietnam  2020                 2.39
16425  South Africa  2020                29.20

[4698 rows x 3 columns]

In [85]:
df_grp = df_3[['country', 'unemployment_15plus']].groupby(by='country').agg(['mean', 'median', 'min', 'max', 'count'])

In [84]:
df_grp

                 unemployment_15plus
                                mean median    min    max count
country
Afghanistan                 6.998000   7.91   1.69  11.70     5
Albania                    12.850000  13.65   3.60  26.50    40
Algeria                    18.005385  16.45   9.82  31.80    26
American Samoa             12.484706  13.00   5.05  19.10    17
Angola                     12.718750  11.89   3.78  23.60     8
...                              ...    ...    ...    ...   ...
Vietnam                     1.890909   1.98   1.00   2.87    22
Wallis et Futuna           56.300000  56.30  56.30  56.30     1
Yemen                      14.404000  15.15   8.34  17.80    10
Zambia                     13.412857  12.95   7.85  19.70    14
Zimbabwe                    7.477778   6.00   4.39  16.90     9

[222 rows x 5 columns]

In [72]:
df_grp.loc['Russia']

unemployment_15plus  mean       7.44069
                     median     7.06000
                     min        4.50000
                     max       13.30000
                     count     29.00000
Name: Russia, dtype: float64

In [97]:
df_grp

                 unemployment_15plus
                                mean median    min    max count
country
Afghanistan                 6.998000   7.91   1.69  11.70     5
Albania                    12.850000  13.65   3.60  26.50    40
Algeria                    18.005385  16.45   9.82  31.80    26
American Samoa             12.484706  13.00   5.05  19.10    17
Angola                     12.718750  11.89   3.78  23.60     8
...                              ...    ...    ...    ...   ...
Vietnam                     1.890909   1.98   1.00   2.87    22
Wallis et Futuna           56.300000  56.30  56.30  56.30     1
Yemen                      14.404000  15.15   8.34  17.80    10
Zambia                     13.412857  12.95   7.85  19.70    14
Zimbabwe                    7.477778   6.00   4.39  16.90     9

[222 rows x 5 columns]

In [92]:
df_grp.columns

MultiIndex([('unemployment_15plus',   'mean'),
            ('unemployment_15plus', 'median'),
            ('unemployment_15plus',    'min'),
            ('unemployment_15plus',    'max'),
            ('unemployment_15plus',  'count')],
           )

In [99]:
df_grp.sort_values(by=[('unemployment_15plus', 'median')])

                 unemployment_15plus
                                mean  median    min    max count
country
Qatar                       0.391875   0.295   0.10   1.48    16
Cambodia                    1.380000   0.795   0.14   7.53    16
Myanmar                     1.940000   0.870   0.50   6.00     5
Chad                        0.915000   0.915   0.70   1.13     2
Rwanda                      6.440000   1.030   0.30  17.40     8
...                              ...     ...    ...    ...   ...
South Africa               27.065217  26.500  22.40  33.30    23
North Macedonia            28.300000  29.000  17.20  38.80    39
Reunion                    29.860000  29.500  19.10  37.70    25
Kosovo                     39.129412  39.700  26.00  57.00    17
Wallis et Futuna           56.300000  56.300  56.30  56.30     1

[222 rows x 5 columns]

In [86]:
help(pd.DataFrame.sort_values)

Help on function sort_values in module pandas.core.frame:

sort_values(self, by: 'IndexLabel', *, axis: 'Axis' = 0, ascending: 'bool | list[bool] | tuple[bool, ...]' = True, inplace: 'bool' = False, kind: 'SortKind' = 'quicksort', na_position: 'str' = 'last', ignore_index: 'bool' = False, key: 'ValueKeyFunc | None' = None) -> 'DataFrame | None'
    Sort by the values along either axis.

    Parameters
    ----------
    by : str or list of str
        Name or list of names to sort by.

        - if `axis` is 0 or `'index'` then `by` may contain index
          levels and/or column labels.
        - if `axis` is 1 or `'columns'` then `by` may contain column
          levels and/or index labels.
    axis : "{0 or 'index', 1 or 'columns'}", default 0
         Axis to be sorted.
    ascending : bool or list of bool, default True
         Sort ascending vs. descending. Specify list for multiple sort
         orders.  If this is a list of bools, must match the length of
         the by.
    inplace : bool, default False
         If True, perform operation in-place.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
         Choice of sorting algorithm. See also :func:`numpy.sort` for more
         information. `mergesort` and `stable` are the only stable algorithms. For
         DataFrames, this option is only applied when sorting on a single
         column or label.
    na_position : {'first', 'last'}, default 'last'
         Puts NaNs at the beginning if `first`; `last` puts NaNs at the
         end.
    ignore_index : bool, default False
         If True, the resulting axis will be labeled 0, 1, …, n - 1.
    key : callable, optional
        Apply the key function to the values
        before sorting. This is similar to the `key` argument in the
        builtin :meth:`sorted` function, with the notable difference that
        this `key` function should be *vectorized*. It should expect a
        ``Series`` and return a Series with the same shape as the input.
        It will be applied to each column in `by` independently.

    Returns
    -------
    DataFrame or None
        DataFrame with sorted values or None if ``inplace=True``.

    See Also
    --------
    DataFrame.sort_index : Sort a DataFrame by the index.
    Series.sort_values : Similar method for a Series.

    Examples
    --------
    >>> df = pd.DataFrame({
    ...     'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    ...     'col2': [2, 1, 9, 8, 7, 4],
    ...     'col3': [0, 1, 9, 4, 2, 3],
    ...     'col4': ['a', 'B', 'c', 'D', 'e', 'F']
    ... })
    >>> df
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Sort by col1

    >>> df.sort_values(by=['col1'])
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    Sort by multiple columns

    >>> df.sort_values(by=['col1', 'col2'])
      col1  col2  col3 col4
    1    A     1     1    B
    0    A     2     0    a
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    Sort Descending

    >>> df.sort_values(by='col1', ascending=False)
      col1  col2  col3 col4
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B
    3  NaN     8     4    D

    Putting NAs first

    >>> df.sort_values(by='col1', ascending=False, na_position='first')
      col1  col2  col3 col4
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B

    Sorting with a key function

    >>> df.sort_values(by='col4', key=lambda col: col.str.lower())
       col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Natural sort with the key argument,
    using the `natsort <https://github.com/SethMMorton/natsort>` package.

    >>> df = pd.DataFrame({
    ...    "time": ['0hr', '128hr', '72hr', '48hr', '96hr'],
    ...    "value": [10, 20, 30, 40, 50]
    ... })
    >>> df
        time  value
    0    0hr     10
    1  128hr     20
    2   72hr     30
    3   48hr     40
    4   96hr     50
    >>> from natsort import index_natsorted
    >>> df.sort_values(
    ...     by="time",
    ...     key=lambda x: np.argsort(index_natsorted(df["time"]))
    ... )
        time  value
    0    0hr     10
    3   48hr     40
    2   72hr     30
    4   96hr     50
    1  128hr     20