In [24]:
import pandas as pd

In [25]:
df = pd.read_csv('../data/raw/googleplaystore.csv')

In [26]:
df.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

In [27]:
df.tail(1)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [28]:
df.shape

(10841, 13)

In [29]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [30]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews             int64
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB

In [32]:
df.describe()

            Rating       Reviews
count  9367.000000  1.084100e+04
mean      4.191513  4.441119e+05
std       0.515735  2.927629e+06
min       1.000000  0.000000e+00
25%       4.000000  3.800000e+01
50%       4.300000  2.094000e+03
75%       4.500000  5.476800e+04
max       5.000000  7.815831e+07

In [13]:
type(1)

int

In [14]:
type(1.2)

float

In [15]:
type('dfgfg')

str

In [16]:
type(df)

pandas.core.frame.DataFrame

In [19]:
df['App']

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: object

In [18]:
type(df['App'])

pandas.core.series.Series

In [33]:
df[ ['App', 'Rating']  ]

                                                     App  Rating
0         Photo Editor & Candy Camera & Grid & ScrapBook     4.1
1                                    Coloring book moana     3.9
2      U Launcher Lite – FREE Live Cool Themes, Hide ...     4.7
3                                  Sketch - Draw & Paint     4.5
4                  Pixel Draw - Number Art Coloring Book     4.3
...                                                  ...     ...
10836                                   Sya9a Maroc - FR     4.5
10837                   Fr. Mike Schmitz Audio Teachings     5.0
10838                             Parkinson Exercices FR     NaN
10839                      The SCP Foundation DB fr nn5n     4.5
10840      iHoroscope - 2018 Daily Horoscope & Astrology     4.5

[10841 rows x 2 columns]

In [38]:
df.sort_values('Reviews').head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9964,SpeedApp EV,AUTO_AND_VEHICLES,NaN,0,48M,5+,Free,0,Everyone,Auto & Vehicles,"July 4, 2018",1.2,6.0 and up
9058,iCluster - The DX-Cluster database,COMMUNICATION,NaN,0,17M,10+,Paid,$0.99,Everyone,Communication,"July 26, 2018",1.7,6.0 and up
9030,KeePass DX Pro,TOOLS,NaN,0,Varies with device,100+,Paid,$5.99,Everyone,Tools,"August 2, 2018",Varies with device,Varies with device
9015,Bodyworks DW,HEALTH_AND_FITNESS,NaN,0,10M,10+,Free,0,Everyone,Health & Fitness,"July 9, 2018",4.2.2,4.1 and up
9014,DW Uninstall Applications,TOOLS,NaN,0,2.5M,10+,Free,0,Everyone,Tools,"February 5, 2017",1.0,2.3 and up
9009,DW Streaming,SOCIAL,NaN,0,Varies with device,"1,000+",Free,0,Everyone,Social,"May 27, 2017",Varies with device,Varies with device
10004,EW MOTION THERAPY,HEALTH_AND_FITNESS,NaN,0,7.1M,10+,Free,0,Everyone,Health & Fitness,"July 9, 2018",4.2.2,4.1 and up
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up
10009,NATIVE ENTERTAINMENT MAGAZINE - ISSUE # 1,NEWS_AND_MAGAZINES,NaN,0,62M,10+,Free,0,Mature 17+,News & Magazines,"December 16, 2017",1,4.1 and up
9997,EW Login,BUSINESS,NaN,0,5.8M,10+,Free,0,Everyone,Business,"December 13, 2017",1.0.0,4.0.3 and up

In [40]:
df.sort_values('Reviews', ascending=False).head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2544,Facebook,SOCIAL,4.1,78158306,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
3943,Facebook,SOCIAL,4.1,78128208,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
381,WhatsApp Messenger,COMMUNICATION,4.4,69119316,Varies with device,"1,000,000,000+",Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
336,WhatsApp Messenger,COMMUNICATION,4.4,69119316,Varies with device,"1,000,000,000+",Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
3904,WhatsApp Messenger,COMMUNICATION,4.4,69109672,Varies with device,"1,000,000,000+",Free,0,Everyone,Communication,"August 3, 2018",Varies with device,Varies with device
2604,Instagram,SOCIAL,4.5,66577446,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
2545,Instagram,SOCIAL,4.5,66577313,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
2611,Instagram,SOCIAL,4.5,66577313,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
3909,Instagram,SOCIAL,4.5,66509917,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
382,Messenger – Text and Video Chat for Free,COMMUNICATION,4.0,56646578,Varies with device,"1,000,000,000+",Free,0,Everyone,Communication,"August 1, 2018",Varies with device,Varies with device

In [55]:
df[  df['Category'] == 'SOCIAL'].sort_values('Reviews', ascending=False).head(20)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2544,Facebook,SOCIAL,4.1,78158306,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
3943,Facebook,SOCIAL,4.1,78128208,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
2604,Instagram,SOCIAL,4.5,66577446,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
2545,Instagram,SOCIAL,4.5,66577313,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
2611,Instagram,SOCIAL,4.5,66577313,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
3909,Instagram,SOCIAL,4.5,66509917,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 31, 2018",Varies with device,Varies with device
2610,Snapchat,SOCIAL,4.0,17015352,Varies with device,"500,000,000+",Free,0,Teen,Social,"July 30, 2018",Varies with device,Varies with device
2550,Snapchat,SOCIAL,4.0,17014787,Varies with device,"500,000,000+",Free,0,Teen,Social,"July 30, 2018",Varies with device,Varies with device
2603,Snapchat,SOCIAL,4.0,17014705,Varies with device,"500,000,000+",Free,0,Teen,Social,"July 30, 2018",Varies with device,Varies with device
3870,Snapchat,SOCIAL,4.0,17000166,Varies with device,"500,000,000+",Free,0,Teen,Social,"July 30, 2018",Varies with device,Varies with device
2546,Facebook Lite,SOCIAL,4.3,8606259,Varies with device,"500,000,000+",Free,0,Teen,Social,"August 1, 2018",Varies with device,Varies with device
4105,Facebook Lite,SOCIAL,4.3,8595964,Varies with device,"500,000,000+",Free,0,Teen,Social,"August 1, 2018",Varies with device,Varies with device
6373,VK,SOCIAL,3.8,5793284,Varies with device,"100,000,000+",Free,0,Mature 17+,Social,"August 3, 2018",Varies with device,Varies with device
3945,Tik Tok - including musical.ly,SOCIAL,4.4,5637451,59M,"100,000,000+",Free,0,Teen,Social,"August 3, 2018",8.0.0,4.1 and up
2554,Google+,SOCIAL,4.2,4831125,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 26, 2018",Varies with device,Varies with device
4144,Google+,SOCIAL,4.2,4828372,Varies with device,"1,000,000,000+",Free,0,Teen,Social,"July 26, 2018",Varies with device,Varies with device
2552,Pinterest,SOCIAL,4.6,4305441,Varies with device,"100,000,000+",Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
2612,Pinterest,SOCIAL,4.6,4305441,Varies with device,"100,000,000+",Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
4088,Pinterest,SOCIAL,4.6,4300936,Varies with device,"100,000,000+",Free,0,Teen,Social,"August 3, 2018",Varies with device,Varies with device
2623,Tango - Live Video Broadcast,SOCIAL,4.3,3806669,Varies with device,"100,000,000+",Free,0,Mature 17+,Social,"August 1, 2018",Varies with device,Varies with device

In [57]:
df[  df['Reviews'] < 3000000 ].sort_values('Reviews', ascending=False).head(20)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2548,Tumblr,SOCIAL,4.4,2955326,Varies with device,"100,000,000+",Free,0,Mature 17+,Social,"August 1, 2018",Varies with device,Varies with device
2599,Tumblr,SOCIAL,4.4,2955325,Varies with device,"100,000,000+",Free,0,Mature 17+,Social,"August 1, 2018",Varies with device,Varies with device
4586,Tumblr,SOCIAL,4.4,2953886,Varies with device,"100,000,000+",Free,0,Mature 17+,Social,"August 1, 2018",Varies with device,Varies with device
4715,Wattpad 📖 Free Books,BOOKS_AND_REFERENCE,4.6,2915189,Varies with device,"100,000,000+",Free,0,Teen,Books & Reference,"August 1, 2018",Varies with device,Varies with device
139,Wattpad 📖 Free Books,BOOKS_AND_REFERENCE,4.6,2914724,Varies with device,"100,000,000+",Free,0,Teen,Books & Reference,"August 1, 2018",Varies with device,Varies with device
9166,Modern Combat 5: eSports FPS,GAME,4.3,2903386,58M,"100,000,000+",Free,0,Mature 17+,Action,"July 24, 2018",3.2.1c,4.0 and up
395,"GO SMS Pro - Messenger, Free Themes, Emoji",COMMUNICATION,4.4,2876500,24M,"100,000,000+",Free,0,Everyone,Communication,"August 1, 2018",7.73,4.0 and up
6849,Bubble Witch 2 Saga,FAMILY,4.3,2838064,Varies with device,"100,000,000+",Free,0,Everyone,Casual,"August 6, 2018",Varies with device,Varies with device
4587,Tinder,LIFESTYLE,4.0,2789775,68M,"100,000,000+",Free,0,Mature 17+,Lifestyle,"August 2, 2018",9.5.0,4.4 and up
2784,eBay: Buy & Sell this Summer - Discover Deals ...,SHOPPING,4.4,2788923,Varies with device,"100,000,000+",Free,0,Teen,Shopping,"July 30, 2018",Varies with device,Varies with device
2738,eBay: Buy & Sell this Summer - Discover Deals ...,SHOPPING,4.4,2788923,Varies with device,"100,000,000+",Free,0,Teen,Shopping,"July 30, 2018",Varies with device,Varies with device
2774,eBay: Buy & Sell this Summer - Discover Deals ...,SHOPPING,4.4,2788923,Varies with device,"100,000,000+",Free,0,Teen,Shopping,"July 30, 2018",Varies with device,Varies with device
2662,eBay: Buy & Sell this Summer - Discover Deals ...,SHOPPING,4.4,2788923,Varies with device,"100,000,000+",Free,0,Teen,Shopping,"July 30, 2018",Varies with device,Varies with device
4068,eBay: Buy & Sell this Summer - Discover Deals ...,SHOPPING,4.4,2788460,Varies with device,"100,000,000+",Free,0,Teen,Shopping,"July 30, 2018",Varies with device,Varies with device
3493,SwiftKey Keyboard,PRODUCTIVITY,4.5,2764964,Varies with device,"100,000,000+",Free,0,Everyone,Productivity,"August 2, 2018",Varies with device,Varies with device
1992,Hill Climb Racing 2,GAME,4.6,2750645,Varies with device,"100,000,000+",Free,0,Everyone,Racing,"August 2, 2018",1.17.2,4.2 and up
1743,Hill Climb Racing 2,GAME,4.6,2750410,Varies with device,"100,000,000+",Free,0,Everyone,Racing,"August 2, 2018",1.17.2,4.2 and up
3523,Google Drive,PRODUCTIVITY,4.4,2731211,Varies with device,"1,000,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
3565,Google Drive,PRODUCTIVITY,4.4,2731211,Varies with device,"1,000,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
3454,Google Drive,PRODUCTIVITY,4.4,2731171,Varies with device,"1,000,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device

In [59]:
df[ (df['Category'] == 'SOCIAL') & ( df['Reviews'] < 3000000 ) ].sort_values('Reviews', ascending=False).head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2548,Tumblr,SOCIAL,4.4,2955326,Varies with device,"100,000,000+",Free,0,Mature 17+,Social,"August 1, 2018",Varies with device,Varies with device
2599,Tumblr,SOCIAL,4.4,2955325,Varies with device,"100,000,000+",Free,0,Mature 17+,Social,"August 1, 2018",Varies with device,Varies with device
4586,Tumblr,SOCIAL,4.4,2953886,Varies with device,"100,000,000+",Free,0,Mature 17+,Social,"August 1, 2018",Varies with device,Varies with device
3951,BIGO LIVE - Live Stream,SOCIAL,4.4,2349421,39M,"100,000,000+",Free,0,Teen,Social,"July 27, 2018",4.1.0,4.0 and up
2622,Path,SOCIAL,4.4,1520959,Varies with device,"10,000,000+",Free,0,Teen,Social,"May 9, 2018",Varies with device,Varies with device

In [63]:
df[ (df['Category'] == 'HOUSE_AND_HOME') | (df['Category'] == 'FINANCE')].sort_values('Reviews', ascending=False).head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1173,Chase Mobile,FINANCE,4.6,1374549,32M,"10,000,000+",Free,0,Everyone,Finance,"July 23, 2018",3.52,5.0 and up
1088,Bank of Brazil,FINANCE,4.5,1336246,39M,"10,000,000+",Free,0,Everyone,Finance,"August 3, 2018",6.39.1.4,4.1 and up
1059,Itau bank,FINANCE,4.2,957973,40M,"10,000,000+",Free,0,Everyone,Finance,"July 30, 2018",6.5.7,4.2 and up
7455,Credit Karma,FINANCE,4.7,706618,Varies with device,"10,000,000+",Free,0,Everyone,Finance,"July 31, 2018",Varies with device,Varies with device
1114,Credit Karma,FINANCE,4.7,706302,Varies with device,"10,000,000+",Free,0,Everyone,Finance,"July 31, 2018",Varies with device,Varies with device

In [66]:
df['Category|Genres'] = df['Category'] + ' | ' + df['Genres']

In [68]:
df['Reviews/Rating'] = df['Reviews'] / df['Rating']

In [69]:
df.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Category|Genres,Reviews/Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,ART_AND_DESIGN | Art & Design,38.780488
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,ART_AND_DESIGN | Art & Design;Pretend Play,247.948718
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,ART_AND_DESIGN | Art & Design,18619.148936
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,ART_AND_DESIGN | Art & Design,47920.888889
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,ART_AND_DESIGN | Art & Design;Creativity,224.883721
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up,ART_AND_DESIGN | Art & Design,37.954545
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up,ART_AND_DESIGN | Art & Design,46.842105
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up,ART_AND_DESIGN | Art & Design,8979.268293
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up,ART_AND_DESIGN | Art & Design,3134.318182
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up,ART_AND_DESIGN | Art & Design;Creativity,25.744681

In [70]:
df.to_csv('../data/processed/app.csv')