In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [9]:
# Простая регрессионная модель.
# 1. Загрузка данных
# 2. Предварительная обработка данных
# 3. Выбор целевой переменной и признаков
# 4. Разделение выборки на обучающую и тестовую
# 5. Обучение модели
# 6. Получение предсказаний и оценка качества
# 7. Анализ коэффициентов модели

In [19]:
df = pd.read_csv('../data/raw/insurance.csv')

In [20]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [22]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [23]:
df_processed = pd.get_dummies(df, columns=['sex', 'smoker', 'region'], drop_first=True)

In [24]:
df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1338 non-null   int64
 1   bmi               1338 non-null   float64
 2   children          1338 non-null   int64
 3   charges           1338 non-null   float64
 4   sex_male          1338 non-null   bool
 5   smoker_yes        1338 non-null   bool
 6   region_northwest  1338 non-null   bool
 7   region_southeast  1338 non-null   bool
 8   region_southwest  1338 non-null   bool
dtypes: bool(5), float64(2), int64(2)
memory usage: 48.5 KB

In [26]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [27]:
y = df_processed['charges']
X = df_processed.drop('charges', axis=1)

In [28]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [29]:
X

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,False,True,False,False,True
1,18,33.770,1,True,False,False,True,False
2,28,33.000,3,True,False,False,True,False
3,33,22.705,0,True,False,True,False,False
4,32,28.880,0,True,False,True,False,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,True,False,True,False,False
1334,18,31.920,0,False,False,False,False,False
1335,18,36.850,0,False,False,False,True,False
1336,21,25.800,0,False,False,False,False,True
1337,61,29.070,0,False,True,True,False,False

In [30]:
y.shape

(1338,)

In [31]:
X.shape

(1338, 8)

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [48]:
X_train

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
1261,28,37.100,1,True,False,False,False,True
816,24,24.225,0,False,False,True,False,False
581,19,30.590,0,True,False,True,False,False
1328,23,24.225,2,False,False,False,False,False
492,18,25.080,0,False,False,False,False,False
...,...,...,...,...,...,...,...,...
73,58,32.010,1,True,False,False,True,False
1142,52,24.860,0,False,False,False,True,False
998,33,36.290,3,False,False,False,False,False
206,59,26.400,0,True,False,False,True,False
867,57,43.700,1,True,False,False,False,True

In [49]:
X_train.shape

(1070, 8)

In [50]:
X_test.shape

(268, 8)

In [51]:
y_train.shape

(1070,)

In [52]:
y_test.shape

(268,)

In [53]:
model = LinearRegression()

In [54]:
model.fit(X_train, y_train)

LinearRegression()

In [55]:
predictions = model.predict(X_test)

In [58]:
mae = mean_absolute_error(y_test, predictions)

In [59]:
mse = mean_squared_error(y_test, predictions)

In [60]:
rmse = np.sqrt(mse)

In [61]:
r2 = r2_score(y_test, predictions)

In [68]:
df['charges'].describe()

count     1338.000000
mean     13270.422265
std      12110.011237
min       1121.873900
25%       4740.287150
50%       9382.033000
75%      16639.912515
max      63770.428010
Name: charges, dtype: float64

In [66]:
print(f'mae = {mae:.2f}')
print(f'mse = {mse:.2f}')
print(f'rmse = {rmse:.2f}')
print(f'R^2 = {r2:.2f}')

mae = 3920.32
mse = 33680468.38
rmse = 5803.49
R^2 = 0.78

In [69]:
model.coef_

array([  256.94295222,   337.67931668,   552.8415818 ,  -253.53277438,
       23660.10485472,    56.31627462,  -845.43390866,  -845.69969435])

In [70]:
X.columns

Index(['age', 'bmi', 'children', 'sex_male', 'smoker_yes', 'region_northwest',
       'region_southeast', 'region_southwest'],
      dtype='object')

In [71]:
coeffs = pd.DataFrame(model.coef_, X.columns, columns=['Coefficients'])

In [74]:
coeffs.sort_values('Coefficients')

                  Coefficients
region_southwest   -845.699694
region_southeast   -845.433909
sex_male           -253.532774
region_northwest     56.316275
age                 256.942952
bmi                 337.679317
children            552.841582
smoker_yes        23660.104855